# For more information: https://laravel.com/docs/sail
services:
    laravel.test:
        container_name: laravel-app
        image: jkpraja/laravel-app:$latest
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '80:8000'
        #environment:
        #    WWWUSER: '${WWWUSER}'
        #    LARAVEL_SAIL: 1
        #    XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
        #    XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
    mysql:
        container_name: mysql-db
        image: 'mysql:8.0'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sailmysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
          test: ["CMD-SHELL", "test -d '/var/lib/mysql/'"]
          retries: 3
          timeout: 5s
networks:
    sail:
        driver: bridge
volumes:
    sailmysql:
        driver: local
