# For more information: https://laravel.com/docs/sail
services:
    laravel-app:
        container_name: laravel-app
        image: jkpraja/laravel-prod-app:latest
        #extra_hosts:
        #    - 'host.docker.internal:host-gateway'
        ports:
            - '8000:9000'
        volumes:
            - 'blogx:/var/www/blogx'
        networks:
            - sail
        #depends_on:
        #    - database
    database:
        container_name: mysql-db
        image: 'mysql:8.0'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sailmysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
          test: ["CMD-SHELL", "test -d '/var/lib/mysql/blogx'"]
          retries: 5
          timeout: 10s
    web-server:
        container_name: web-server
        image: jkpraja/laravel-server:latest
        ports:
          - "80:80"
        volumes:
          - blogx:/var/www/blogx
        #depends_on:
        #    - laravel-app
        networks:
            - sail
networks:
    sail:
    #    driver: bridge
volumes:
    blogx:
    sailmysql:
#        driver: local
